services:
  example-handler:
    image: public.ecr.aws/lambda/java:21
    build:
      context: ./java
      dockerfile: Dockerfile
    container_name: example-handler
    ports:
      - 9000:8080
networks:
  lambda: {}
